name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: docker login --username adi7312 --password ${{ secrets.GH_PAT }} ghcr.io; docker build --build-arg S_PASS=${{ secrets.S_PASS }} --tag ghcr.io/adi7312/vuln-scan:latest . ; docker push ghcr.io/adi7312/vuln-scan:latest
      
      
      
